export const LOGIN_USER = 'LOGIN_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const AUTH_CHECK_USER = 'AUTH_CHECK_USER';
export const SIGNUP_RESET = 'SIGNUP_RESET';
export const GET_COUNTRIES_FILTER = 'GET_COUNTRIES_FILTER';
export const VERIFY_USER = 'VERIFY_USER';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const PRODUCT_UPLOADED = 'PRODUCT_UPLOADED';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const REMOVE_REDIRECT = 'REMOVE_REDIRECT';

export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const ADD_ITEM_TO_BUY = 'ADD_ITEM_TO_BUY';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const GET_ITEMS_IN_CART = 'GET_ITEMS_IN_CART';